apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: second-application-ingress
spec:
  rules:
    - http:
        paths:
          - path: /pingpong
            backend:
              serviceName: second-application-svc
              servicePort: 2345
