apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-application-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-application
  template:
    metadata:
      labels:
        app: main-application
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
      containers:
        - name: generate-timestamp
          image: jonestpg/1.10-generate-timestamp
          volumeMounts:
          - name: shared-volume
            mountPath: /usr/src/app/files
        - name: output-timestamp
          image: jonestpg/1.10-output-timestamp
          volumeMounts:
          - name: shared-volume
            mountPath: /usr/src/app/files
